### PR TITLE
Avoid the use of java.util.Function beans

### PR DESCRIPTION
**Pull request by markusheiden**
These are considered by Spring Cloud Stream's FunctionCatalog and cause trouble.

### CODE REVIEW

**Comment by stepio** [comment]
Hello, thanks for your contribution!

Would you please share a bit more details on why you started this change? What is the problem you're trying to solve here? Have you encountered an error?

**Comment by markusheiden** [comment]
We are using Spring Cloud Config which uses Spring Cloud Bus which uses Spring Cloud Stream. Spring Cloud Stream uses all beans of type `java.util.Function` (and some more) for purposes I don't understand. But when disabling Spring Cloud Config existing functions will be used to provide some kind of functionality (or auto config?) that results in startup errors when coffee-boots is active.

So to not let coffee-boots interfere with Spring Cloud Stream at all, I introduced a distinct interface for coffee-bots with this MR.

**Comment by stepio** [comment]
Sounds very much reasonable, thanks for clarification!

@markusheiden , would you please rebase this CR? I think I fixed the Sonar config.

**Comment by markusheiden** [comment]
I rebased the PR branch upon upstream/master, but still:
```
Failed to execute goal org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.1.2184:sonar (default) on project coffee-boots: Project not found. Please check the ‘sonar.projectKey’ and ‘sonar.organization’ properties, the ‘SONAR_TOKEN’ environment variable, or contact the project administrator
```

**Comment by stepio** [comment]
Managed to build in a branch:
https://app.travis-ci.com/github/stepio/coffee-boots/builds/251292889

The code looks reasonable - merging, thanks!

**Comment by markusheiden** [comment]
Do you plan to do a release then?

**Comment by stepio** [comment]
Done! Hope I remembered the process correctly - if yes, new binaries should be available soon.
Will double-check tomorrow.

**Comment by markusheiden** [comment]
It works. Thanks!

**Pull request merged**
